{
 "title": "udacity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Final Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"localhost\",namespace=\"default\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{node=\"localhost\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Namespace: Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{node=\"localhost\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Span Traces by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(jaeger:traces_total{service=\"frontend\"})",
     "legendFormat": "Frontend Traces"
    },
    {
     "expr": "sum(jaeger:traces_total{service=\"backend\"})",
     "legendFormat": "Backend Traces"
    }
   ]
  },
  { "title": "Basic KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Backend Uptime [1 Day]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum_over_time(up{pod=~\"backend-859f558bbd-ld8n4|backend-859f558bbd-mmd5x|backend-859f558bbd-gv8dm\",service=\"backend\"}[7d]) * 15 / (604800/7)"
    }
   ]
  },
  {
   "title": "Backend HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 34 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{service=\"backend\",status=~\"200|404|403|500|503\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(flask_http_request_total{service=~\"backend\", status=~\"403|404|500|503\"}) by (status, container)",
     "legendFormat": "{{container}} -> status_code: {{status}} "
    }
   ]
  },
  {
   "title": "Frontend Uptime [1 Day]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum_over_time(up{pod=~\"frontend-994b48c4f-mwdpj|frontend-994b48c4f-p5q8t|frontend-994b48c4f-8mdgq\",service=\"frontend\"}[7d]) * 15 / (604800 / 7)"
    }
   ]
  },
  {
   "title": "Frontend HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 45 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{service=\"frontend\", status=~\"200|404|403|500|503\"})",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(flask_http_request_total{service=~\"frontend\", status=~\"500|503|404|403\"}) by (status, container)",
     "legendFormat": "{{container}} -> status_code: {{status}} "
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{service=~\"backend|frontend\", status=~\"403|404|500|503\"}) by (service)"
    }
   ]
  }
 ]
}